
export const marketData = [
  { key: 'wheat', name: 'Wheat (Quintal)', price: '₹2,350', trend: 'up', change: '+1.2%' },
  { key: 'paddy', name: 'Paddy (Quintal)', price: '₹2,180', trend: 'stable', change: '0.0%' },
  { key: 'maize', name: 'Maize (Quintal)', price: '₹2,050', trend: 'down', change: '-0.8%' },
  { key: 'barley', name: 'Barley (Quintal)', price: '₹1,750', trend: 'up', change: '+0.5%' },
  { key: 'sorghum', name: 'Sorghum (Jowar) (Quintal)', price: '₹2,900', trend: 'down', change: '-1.5%' },
  { key: 'pearl_millet', name: 'Pearl Millet (Bajra) (Quintal)', price: '₹2,450', trend: 'stable', change: '0.0%' },
  { key: 'finger_millet', name: 'Finger Millet (Ragi) (Quintal)', price: '₹3,500', trend: 'up', change: '+2.1%' },
  { key: 'chickpea', name: 'Chickpea (Gram) (Quintal)', price: '₹6,200', trend: 'up', change: '+3.0%' },
  { key: 'pigeon_pea', name: 'Pigeon Pea (Tur/Arhar) (Quintal)', price: '₹9,800', trend: 'down', change: '-2.0%' },
  { key: 'lentil', name: 'Lentil (Masur) (Quintal)', price: '₹6,550', trend: 'up', change: '+1.8%' },
  { key: 'green_gram', name: 'Green Gram (Moong) (Quintal)', price: '₹8,500', trend: 'stable', change: '+0.1%' },
  { key: 'black_gram', name: 'Black Gram (Urad) (Quintal)', price: '₹8,200', trend: 'down', change: '-1.1%' },
  { key: 'soybean', name: 'Soybean (Quintal)', price: '₹4,800', trend: 'up', change: '+2.5%' },
  { key: 'groundnut', name: 'Groundnut (Quintal)', price: '₹6,000', trend: 'stable', change: '0.0%' },
  { key: 'mustard', name: 'Mustard (Quintal)', price: '₹5,650', trend: 'up', change: '+1.0%' },
  { key: 'sunflower', name: 'Sunflower (Quintal)', price: '₹4,900', trend: 'down', change: '-0.5%' },
  { key: 'sugarcane', name: 'Sugarcane (Tonne)', price: '₹3,150', trend: 'stable', change: '0.0%' },
  { key: 'cotton', name: 'Cotton (Quintal)', price: '₹7,100', trend: 'up', change: '+1.4%' },
  { key: 'turmeric', name: 'Turmeric (Quintal)', price: '₹14,500', trend: 'down', change: '-3.2%' },
  { key: 'tomato', name: 'Tomato (Kg)', price: '₹25', trend: 'up', change: '+5.0%' },
  { key: 'onion', name: 'Onion (Kg)', price: '₹30', trend: 'down', change: '-8.0%' },
  { key: 'potato', name: 'Potato (Kg)', price: '₹20', trend: 'stable', change: '0.0%' },
  { key: 'brinjal', name: 'Brinjal (Kg)', price: '₹22', trend: 'up', change: '+2.0%' },
  { key: 'cauliflower', name: 'Cauliflower (Kg)', price: '₹35', trend: 'stable', change: '+0.5%' },
  { key: 'cabbage', name: 'Cabbage (Kg)', price: '₹18', trend: 'down', change: '-4.0%' },
  { key: 'okra', name: "Okra (Lady's Finger) (Kg)", price: '₹40', trend: 'up', change: '+3.5%' },
  { key: 'chilli', name: 'Chilli (Green) (Kg)', price: '₹60', trend: 'up', change: '+10.1%' },
  { key: 'ginger', name: 'Ginger (Kg)', price: '₹120', trend: 'down', change: '-5.5%' },
  { key: 'garlic', name: 'Garlic (Kg)', price: '₹150', trend: 'stable', change: '0.0%' },
  { key: 'peas', name: 'Peas (Kg)', price: '₹45', trend: 'up', change: '+1.5%' },
  { key: 'carrot', name: 'Carrot (Kg)', price: '₹30', trend: 'down', change: '-2.0%' },
  { key: 'radish', name: 'Radish (Kg)', price: '₹25', trend: 'stable', change: '0.0%' },
  { key: 'mango', name: 'Mango (Alphonso) (Kg)', price: '₹250', trend: 'up', change: '+12.0%' },
  { key: 'banana', name: 'Banana (Dozen)', price: '₹40', trend: 'stable', change: '+0.2%' },
  { key: 'apple', name: 'Apple (Shimla) (Kg)', price: '₹120', trend: 'down', change: '-4.5%' },
  { key: 'orange', name: 'Orange (Nagpur) (Kg)', price: '₹60', trend: 'up', change: '+3.0%' },
  { key: 'grapes', name: 'Grapes (Kg)', price: '₹80', trend: 'stable', change: '0.0%' },
  { key: 'pomegranate', name: 'Pomegranate (Kg)', price: '₹140', trend: 'up', change: '+5.8%' },
  { key: 'coriander', name: 'Coriander (Dhaniya) (Kg)', price: '₹50', trend: 'down', change: '-10.0%' },
  { key: 'cumin', name: 'Cumin (Jeera) (Quintal)', price: '₹25,000', trend: 'up', change: '+4.0%' },
  { key: 'fennel', name: 'Fennel (Saunf) (Quintal)', price: '₹18,000', trend: 'stable', change: '0.0%' },
  { key: 'black_pepper', name: 'Black Pepper (Kg)', price: '₹650', trend: 'down', change: '-1.2%' },
  { key: 'cardamom', name: 'Cardamom (Kg)', price: '₹1,800', trend: 'up', change: '+6.7%' },
];
